#Docker-compose.yml (production)
version: '3'
services:
  web:
    build: .
    image: devconnector
    environment:
      - PORT=5000
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - db
    ports:
      - "5000:5000"
      - "9229:9229"
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev-server"]
  
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./tmp:/docker-entrypoint-initdb.d